logging:
  level: DEBUG
  output: stdout
database:
  connection_string: "postgres://username:password@localhost/database"
admin:
  listen_address: ":8000"
mailgun:
  listen_address: ":8001"
smtp_server:
  listen_address: ":8025"
